displayName: GeoBlock
type: middleware

import: github.com/PascalMinder/GeoBlock

summary: 'block request based on their country of origin'

testData:
  allowLocalRequests: false
  logLocalRequests: false
  logAllowedRequests: false
  logApiRequests: true
  api: "https://get.geojs.io/v1/ip/country/{ip}"
  cacheAize: 15
  forceMonthlyUpdate: true
  allowUnknownCountries: false
  unknownCountryApiResponse: "nil"
  countries:
    - CH